# pubspec.yaml
name: neural_learn
description: "NeuralLearn - Offline AI Learning Companion"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this
    sdk: flutter
  intl: ^0.20.2 # Add this
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdfviewer: ^32.2.7
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true # Set this to true
  uses-material-design: true

  assets:
    - assets/books/10/english/
    - assets/books/10/hindi/
    - assets/books/10/math/
    - assets/books/10/science/
    - assets/books/10/social_studies/
