# pubspec.yaml
name: neural_learn
description: "NeuralLearn - Offline AI Learning Companion"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdfviewer: ^32.2.7
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/books/10/english/
    - assets/books/10/hindi/
    - assets/books/10/math/
    - assets/books/10/science/
    - assets/books/10/social_studies/